// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	model "github.com/Tracking-Detector/td-backend/go/td_common/model"
	mock "github.com/stretchr/testify/mock"
)

// IExportJob is an autogenerated mock type for the IExportJob type
type IExportJob struct {
	mock.Mock
}

// Execute provides a mock function with given fields: exporter, reducer, dataset
func (_m *IExportJob) Execute(exporter *model.Exporter, reducer string, dataset string) *model.ExportMetrics {
	ret := _m.Called(exporter, reducer, dataset)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *model.ExportMetrics
	if rf, ok := ret.Get(0).(func(*model.Exporter, string, string) *model.ExportMetrics); ok {
		r0 = rf(exporter, reducer, dataset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ExportMetrics)
		}
	}

	return r0
}

// NewIExportJob creates a new instance of IExportJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExportJob(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExportJob {
	mock := &IExportJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
