load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "model",
    srcs = [
        "dataset.py",
        "model.py",
        "training_run.py",
    ],
    visibility = ["//visibility:public"],
)
