name: CI

on: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/test.yaml
  
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: |
          bazel run //go/td_dataset/cmd:push -- --tag ${{ github.ref_name }}
          bazel run //go/td_dispatcher/cmd:push -- --tag ${{ github.ref_name }}
          bazel run //go/td_download/cmd:push -- --tag ${{ github.ref_name }}
          bazel run //go/td_export/cmd:push -- --tag ${{ github.ref_name }}
          bazel run //go/td_exporter/cmd:push -- --tag ${{ github.ref_name }}
          bazel run //go/td_model/cmd:push -- --tag ${{ github.ref_name }}
          bazel run //go/td_request/cmd:push -- --tag ${{ github.ref_name }}
          bazel run //go/td_user/cmd:push -- --tag ${{ github.ref_name }}
