name: CI
on:
  workflow_call:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //...
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel test //... --test_tag_filters=unittest --jobs=auto
  # integrationtests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - uses: bazelbuild/setup-bazelisk@v3
  #     - name: Mount bazel cache
  #       uses: actions/cache@v4
  #       with:
  #         path: "~/.cache/bazel"
  #         key: bazel
  #     - run: bazel test //... --test_tag_filters=integration --test_timeout=75 --jobs=1

  
